volumes:
  static:
  media:
  pg_data:

services:
  db:
    image: postgres:13.10
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./madhouse/
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - backend

  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379
