# Generated by Django 5.1.2 on 2024-11-19 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate',
            field=models.ForeignKey(blank=True, help_text='Обязательно выбирать', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.maindata', verbose_name='Связь с основными данными'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Обязательно выбирать', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.maindata', verbose_name='Связь с основными данными'),
        ),
        migrations.AlterField(
            model_name='serviceexample',
            name='service_example',
            field=models.ForeignKey(blank=True, help_text='Обязательно выбирать', null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.maindata', verbose_name='Связь с основными данными'),
        ),
    ]
